### ISSUE TITLE
Mapwidget can't find places

### ISSUE THREAD

**Issue by djowett-ftw** [4teamwork/ftw.geo#27]
probably an issue in collective.geo.* but raising here for internal visibility

The mapwidget with Googlemaps can't find a location like Bern.

<img width="1183" alt="Screenshot 2020-01-28 at 13 46 18" src="https://user-images.githubusercontent.com/54800639/73265263-df183800-41d4-11ea-948a-8ef3c11b9ca3.png">

**Comment by maethu** [comment]
@djowett-ftw This is because the key your are using is not working for geo look ups.

I'll close this issue, if it is something else please reopen :blush:
